### PR TITLE
Fix issue with search strings which are valid regexes

### LINKED ISSUE #179: Valid regex terms in search find unexpected matches
A search for 'beech \w house' will show all doctors for each matching surgery due to the way the regex is created for each search term.

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
Fixes #179

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/gp-finder succeeded (http://gp-finder-pr-178.dev.beta.nhschoices.net)

File: app/lib/utils/gpDataMapper.js [hunk 1]
```diff
@@ -7,23 +7,26 @@ function isNonEmptyTerm(term) {
...
+      .filter(isNotTitle)
+      .map(term => term.toLowerCase());
 
-    termRegexes.forEach((regexp) => {
+    searchTerms.forEach((term) => {
       filteredDocs = filteredDocs
         .concat(
           gpData.doctors
-            .filter(doctor => regexp.test(doctor.name))
+            .filter(doctor => doctor.name && doctor.name.toLowerCase().includes(term))
```
Comment (st3v3nhunt) [inline app/lib/utils/gpDataMapper.js]: Rather than combining this logic into a single filter I think it would be easier to read if split across two filters.

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/gp-finder succeeded (http://gp-finder-pr-178.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/gp-finder succeeded (http://gp-finder-pr-178.dev.beta.nhschoices.net)
